Repository vmware-clarity/starters, pull requests merged in 2022-08, with the labels that each got.

#70 feat: set virtual scroll rows to be fixed height
  grid-demo/src/app/angular/final-demo/final-demo.component.html
  grid-demo/src/app/angular/final-demo/final-demo.component.scss
  grid-demo/src/app/angular/lazy-loading-rows/lazy-loading-rows.component.html
  grid-demo/src/app/angular/lazy-loading-rows/lazy-loading-rows.component.scss
  grid-demo/src/app/angular/row-dom-performance/row-dom-performance.component.html
  grid-demo/src/app/angular/row-dom-performance/row-dom-performance.component.scss
Labels: feature

#77 fix(grid-demo): maintain active cell in virtual rows correctly
  grid-demo/src/app/angular/row-dom-performance/custom-clr-virtual-rows.directive.ts
Labels: bug

#65 fix: drop column when focusing on data cell
  grid-demo/src/app/angular/column-ordering/custom-clr-column-ordering-column.directive.ts
  grid-demo/src/app/angular/column-ordering/custom-clr-column-ordering-grid.directive.ts
  grid-demo/src/app/angular/column-ordering/custom-clr-column-ordering.service.ts
Labels: bug

#69 feat: add column ordering events to support aria-live
  grid-demo/src/app/angular/column-ordering/column-ordering.component.html
  grid-demo/src/app/angular/column-ordering/column-ordering.component.ts
  grid-demo/src/app/angular/column-ordering/custom-clr-column-ordering-column.directive.ts
  grid-demo/src/app/angular/column-ordering/custom-clr-column-ordering-grid.directive.ts
Labels: feature

#71 feat: update demo comments
  grid-demo/src/app/angular/column-ordering/column-ordering.component.html
  grid-demo/src/app/angular/lazy-loading-rows/lazy-loading-rows.component.html
  grid-demo/src/app/angular/row-dom-performance/row-dom-performance.component.html
Labels: feature

#93 feat(grid-demo): add note about row selection and clickable elements
  grid-demo/src/app/angular/advanced-row-selection/advanced-row-selection.component.html
Labels: scope: advanced-row-selection

#92 fix(grid-demo): make selection cell click not deselect elements
  grid-demo/src/app/angular/advanced-row-selection/custom-clr-advanced-selection.directive.ts
Labels: scope: advanced-row-selection
